[package]
name = "noprop"
version = "0.1.0"
edition = "2024"
rust-version = "1.88"
license = "MIT"
description = "Imperative property-based testing with no dependencies and no macro DSL"
homepage = "https://github.com/sile/noprop"
repository = "https://github.com/sile/noprop"
readme = "README.md"
categories = ["development-tools::testing"]

[dependencies]

[workspace]
members = ["benchmark"]
