[package]
name = "noprop"
version = "0.0.2"
edition = "2024"
rust-version = "1.88"
license = "MIT"
description = "Imperative property-based testing library with no dependencies, no macros, no unsafe, and no implicit I/O"
homepage = "https://github.com/sile/noprop"
repository = "https://github.com/sile/noprop"
readme = "README.md"
categories = ["development-tools::testing"]

[dependencies]

[dev-dependencies]
nojson = "0.3"
noargs = "0.4"
proptest = "1.11"
