[package]
name = "noprop"
version = "0.2.0"
edition = "2024"
rust-version = "1.88"
license = "MIT"
description = "Property-based testing with plain functions, ordinary control flow, and no dependencies"
homepage = "https://github.com/sile/noprop"
repository = "https://github.com/sile/noprop"
readme = "README.md"
categories = ["development-tools::testing"]

[dependencies]

[workspace]
members = ["benchmark"]
